import { CurveDefinition } from '../types/index.js';

export const curveLibrary: CurveDefinition[] = [
  { name: 'Parabola', formula: 'x^2', description: 'A U-shaped curve defined by y = ax² + bx + c, the graph of a quadratic function.', type: '2d', defaultParams: { a: 1, b: 0, c: 0 } },
  { name: 'Hyperbola', formula: '1/x', description: 'A curve with two branches, each approaching but never touching the axes (asymptotes).', type: '2d' },
  { name: 'Ellipse', formula: 'cos(t), 0.6*sin(t)', description: 'A closed curve where the sum of distances from two foci is constant: x²/a² + y²/b² = 1.', type: 'parametric', paramRange: [0, 6.2832] },
  { name: 'Circle', formula: 'cos(t), sin(t)', description: 'The set of all points equidistant from a center point: x² + y² = r².', type: 'parametric', paramRange: [0, 6.2832] },
  { name: 'Sine', formula: 'sin(x)', description: 'The fundamental periodic wave function, oscillating between -1 and 1.', type: '2d' },
  { name: 'Cosine', formula: 'cos(x)', description: 'Like sine but shifted by π/2; the adjacent/hypotenuse ratio in a right triangle.', type: '2d' },
  { name: 'Tangent', formula: 'tan(x)', description: 'The ratio sin/cos with vertical asymptotes where cos(x) = 0.', type: '2d' },
  { name: 'Lissajous curve', formula: 'sin(3*t + pi/4), sin(2*t)', description: 'Complex patterns from perpendicular oscillations: x = A·sin(at + δ), y = B·sin(bt).', type: 'parametric', paramRange: [0, 6.2832] },
  { name: 'Cycloid', formula: 't - sin(t), 1 - cos(t)', description: 'The curve traced by a point on a rolling circle.', type: 'parametric', paramRange: [0, 18.8496] },
  { name: 'Butterfly curve', formula: 'exp(sin(theta)) - 2*cos(4*theta) + sin((2*theta - pi) / 24)^5', description: 'A beautiful polar curve discovered by Temple Fay, resembling a butterfly.', type: 'polar' },
  { name: 'Archimedean spiral', formula: 'theta', description: 'A spiral with constant distance between turns: r = aθ.', type: 'polar' },
  { name: 'Cardioid', formula: '1 + cos(theta)', description: 'A heart-shaped curve traced by a point on a circle rolling around a fixed circle of equal radius.', type: 'polar' },
  { name: 'Rose curve', formula: 'cos(3*theta)', description: 'A sinusoidal curve in polar form creating petal-like patterns: r = cos(nθ).', type: 'polar' },
  { name: 'Astroid', formula: 'cos(t)^3, sin(t)^3', description: 'A hypocycloid with four cusps: x = a·cos³t, y = a·sin³t.', type: 'parametric', paramRange: [0, 6.2832] },
  { name: 'Lemniscate of Bernoulli', formula: 'sqrt(2*cos(2*theta))', description: 'A figure-eight curve: r² = a²cos(2θ), discovered by Jacob Bernoulli.', type: 'polar' },
  { name: 'Logarithmic spiral', formula: 'exp(0.2*theta)', description: 'A self-similar spiral found in nature (nautilus shells, galaxies): r = ae^(bθ).', type: 'polar' },
  { name: 'Folium of Descartes', formula: '3*sin(t)*cos(t)/(sin(t)^3 + cos(t)^3), 3*sin(t)^2*cos(t)/(sin(t)^3 + cos(t)^3) - 0', description: 'A curve with a loop that crosses itself at the origin.', type: 'parametric', paramRange: [-0.5, 5] },
  { name: 'Limacon', formula: '1 + 2*cos(theta)', description: 'A family of curves including cardioids, generated by a point on a circle rolling around another circle.', type: 'polar' },
  { name: 'Involute of circle', formula: 'cos(t) + t*sin(t), sin(t) - t*cos(t)', description: 'The curve traced by the end of a string unwinding from a circle.', type: 'parametric', paramRange: [0, 12.5664] },
  { name: 'Epitrochoid', formula: '5*cos(t) - 2*cos(5*t/2), 5*sin(t) - 2*sin(5*t/2)', description: 'A curve traced by a point attached to a circle rolling around another circle (Spirograph patterns).', type: 'parametric', paramRange: [0, 12.5664] },
  // 3D surfaces
  { name: 'Saddle surface', formula: 'x^2 - y^2', description: 'A hyperbolic paraboloid with a saddle point at the origin.', type: '3d' },
  { name: 'Paraboloid', formula: 'x^2 + y^2', description: 'A bowl-shaped surface given by z = x² + y².', type: '3d' },
  { name: 'Sinc surface', formula: 'sin(sqrt(x^2 + y^2)) / sqrt(x^2 + y^2 + 0.001)', description: 'The 2D sinc function, a ripple-like surface.', type: '3d' },
  { name: 'Ripple surface', formula: 'sin(sqrt(x^2 + y^2))', description: 'Concentric ripples radiating from the origin: z = sin(√(x² + y²)).', type: '3d' },
  { name: 'Helix', formula: 'cos(t), sin(t), t/5', description: 'A 3D spiral curve winding around an axis at constant rate.', type: 'parametric', paramRange: [0, 18.8496] },
];

export function lookupCurve(name: string): CurveDefinition | undefined {
  const lower = name.toLowerCase();
  return curveLibrary.find(
    (c) =>
      c.name.toLowerCase().includes(lower) ||
      lower.includes(c.name.toLowerCase())
  );
}
